import fs from "fs";
const lines = [];
lines.push("        {/* \u2500\u2500 LORDS OF EASY MONEY \u2014 Daily Quote \u2500\u2500 */}");
lines.push("        \x3cdiv style={{ marginTop: 12, border: \x601px solid \x24{t.borderMid}\x60, background: t.panel, padding: \x2714px 16px\x27, animation: \x27radarFadeUp 0.3s ease-out 0.3s both\x27 }}\x3e");
lines.push("          \x3cdiv style={{ display: \x27flex\x27, alignItems: \x27flex-start\x27, gap: 12, flexWrap: \x27wrap\x27 }}\x3e");
lines.push("            \x3cspan style={{ flexShrink: 0, fontSize: 11, color: t.accent, textTransform: \x27uppercase\x27, letterSpacing: \x270.1em\x27, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22, border: \x601px solid \x24{t.accent}\x60, padding: \x272px 7px\x27, marginTop: 3, whiteSpace: \x27nowrap\x27 }}\x3eLords of Easy Money\x3c/span\x3e");
lines.push("            \x3cdiv style={{ flex: 1, minWidth: 0 }}\x3e");
lines.push("              \x3cdiv style={{ fontSize: 15, color: t.textPrimary, lineHeight: 1.6, fontStyle: \x27italic\x27 }}\x3e\x22{lordsQuote.quote}\x22\x3c/div\x3e");
lines.push("              \x3cdiv style={{ marginTop: 6, display: \x27flex\x27, gap: 10, alignItems: \x27center\x27, flexWrap: \x27wrap\x27 }}\x3e");
lines.push("                \x3cspan style={{ fontSize: 12, color: t.textGhost }}\x3e\u2014 Christopher Leonard\x3c/span\x3e");
lines.push("                \x3cspan style={{ fontSize: 11, color: t.warn, textTransform: \x27uppercase\x27, letterSpacing: \x270.08em\x27, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22, border: \x601px solid \x24{t.warn}40\x60, padding: \x271px 6px\x27 }}\x3e{lordsQuote.theme}\x3c/span\x3e");
lines.push("              \x3c/div\x3e");
lines.push("            \x3c/div\x3e");
lines.push("          \x3c/div\x3e");
lines.push("        \x3c/div\x3e");
lines.push("");
lines.push("        {/* \u2500\u2500 FED REACTOR + MONEY PUMP \u2500\u2500 */}");
lines.push("        \x3cdiv className=\"ms2-grid\" style={{ marginTop: 12, display: \x27grid\x27, gridTemplateColumns: \x271fr 1fr\x27, gap: 12 }}\x3e");
lines.push("");
lines.push("          {/* FED REACTOR */}");
lines.push("          \x3cdiv style={{ border: \x601px solid \x24{t.borderMid}\x60, background: t.panel, padding: \x2720px 16px\x27, animation: \x27radarFadeUp 0.4s ease-out 0.4s both\x27, display: \x27flex\x27, flexDirection: \x27column\x27, alignItems: \x27center\x27 }}\x3e");
lines.push("            \x3cdiv style={{ fontSize: 12, color: t.textSecondary, textTransform: \x27uppercase\x27, letterSpacing: \x270.1em\x27, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22, fontWeight: 700, marginBottom: 16 }}\x3eFED REACTOR \u2014 SYSTEM STATUS\x3c/div\x3e");
lines.push("            {/* Reactor core */}");
lines.push("            \x3cdiv style={{ position: \x27relative\x27, width: 140, height: 140, margin: \x270 auto 16px\x27, flexShrink: 0 }}\x3e");
lines.push("              \x3cdiv style={{ position: \x27absolute\x27, top: 4, right: 4, bottom: 4, left: 4, border: \x602px solid \x24{reactorColor}\x60, borderRadius: \x2750%\x27, animation: \x27reactorRing1 3s ease-in-out infinite\x27 }} /\x3e");
lines.push("              \x3cdiv style={{ position: \x27absolute\x27, top: 18, right: 18, bottom: 18, left: 18, border: \x601px solid \x24{reactorColor}\x60, borderRadius: \x2750%\x27, animation: \x27reactorRing2 3s ease-in-out infinite 0.5s\x27 }} /\x3e");
lines.push("              \x3cdiv style={{ position: \x27absolute\x27, top: 30, right: 30, bottom: 30, left: 30, background: \x60radial-gradient(circle, \x24{reactorColor} 0%, transparent 70%)\x60, borderRadius: \x2750%\x27, animation: \x27reactorPulse 3s ease-in-out infinite\x27 }} /\x3e");
lines.push("              \x3cdiv style={{ position: \x27absolute\x27, top: \x2750%\x27, left: \x2750%\x27, transform: \x27translate(-50%, -50%)\x27, width: 14, height: 14, background: reactorColor, borderRadius: \x2750%\x27, boxShadow: \x600 0 20px \x24{reactorColor}\x60 }} /\x3e");
lines.push("            \x3c/div\x3e");
lines.push("            {/* Status */}");
lines.push("            \x3cdiv style={{ textAlign: \x27center\x27, marginBottom: 16 }}\x3e");
lines.push("              \x3cdiv style={{ fontSize: 13, fontWeight: 700, color: reactorColor, textTransform: \x27uppercase\x27, letterSpacing: \x270.08em\x27, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22 }}\x3e{reactorStatus}\x3c/div\x3e");
lines.push("              \x3cdiv style={{ fontSize: 12, color: t.textGhost, marginTop: 4 }}\x3e{reactorDesc}\x3c/div\x3e");
lines.push("            \x3c/div\x3e");
lines.push("            {/* Rate lever */}");
lines.push("            \x3cdiv style={{ width: \x27100%\x27, paddingTop: 8, borderTop: \x601px solid \x24{t.borderDim}\x60 }}\x3e");
lines.push("              \x3cdiv style={{ display: \x27flex\x27, justifyContent: \x27space-between\x27, fontSize: 11, color: t.textGhost, marginBottom: 6 }}\x3e");
lines.push("                \x3cspan\x3e0% (Easy)\x3c/span\x3e");
lines.push("                \x3cspan style={{ fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22, color: t.textDim, fontSize: 10, textTransform: \x27uppercase\x27, letterSpacing: \x270.06em\x27 }}\x3eRate Lever\x3c/span\x3e");
lines.push("                \x3cspan\x3e5%+ (Tight)\x3c/span\x3e");
lines.push("              \x3c/div\x3e");
lines.push("              \x3cinput type=\"range\" min={0} max={100} value={rateLevel} onChange={e =\x3e setRateLevel(Number(e.target.value))} style={{ width: \x27100%\x27, accentColor: reactorColor, cursor: \x27pointer\x27 }} /\x3e");
lines.push("            \x3c/div\x3e");
lines.push("          \x3c/div\x3e");
lines.push("");
lines.push("          {/* MONEY PUMP */}");
lines.push("          \x3cdiv style={{ border: \x601px solid \x24{t.borderMid}\x60, background: t.panel, padding: \x2720px 16px\x27, animation: \x27radarFadeUp 0.4s ease-out 0.5s both\x27 }}\x3e");
lines.push("            \x3cdiv style={{ fontSize: 12, color: t.textSecondary, textTransform: \x27uppercase\x27, letterSpacing: \x270.1em\x27, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22, fontWeight: 700, marginBottom: 16 }}\x3eQUANTITATIVE EASING \u2014 MONEY FLOW\x3c/div\x3e");
lines.push("            {/* SVG money pump */}");
lines.push("            \x3csvg viewBox=\"0 0 340 110\" style={{ width: \x27100%\x27, marginBottom: 14, overflow: \x27visible\x27 }}\x3e");
lines.push("              \x3ccircle cx=\"44\" cy=\"55\" r=\"30\" fill={isDark ? \x27#0d2a2a\x27 : \x27#e8f5f5\x27} stroke={t.accent} strokeWidth=\"1.5\" /\x3e");
lines.push("              \x3ctext x=\"44\" y=\"50\" fill={t.accent} fontSize=\"10\" fontWeight=\"700\" textAnchor=\"middle\" fontFamily=\"JetBrains Mono, monospace\"\x3eFED\x3c/text\x3e");
lines.push("              \x3ctext x=\"44\" y=\"64\" fill={t.textGhost} fontSize=\"8\" textAnchor=\"middle\" fontFamily=\"JetBrains Mono, monospace\"\x3eReserve\x3c/text\x3e");
lines.push("              \x3cpath d=\"M76 55 L264 55\" stroke={\x60\x24{t.accent}40\x60} strokeWidth=\"2\" strokeDasharray=\"4 4\" /\x3e");
lines.push("              \x3ccircle r=\"5\" fill={t.accent} opacity=\"0.9\"\x3e\x3canimateMotion dur=\"2.5s\" repeatCount=\"indefinite\" path=\"M76 55 L264 55\" /\x3e\x3c/circle\x3e");
lines.push("              \x3ccircle r=\"3\" fill={t.accent} opacity=\"0.5\"\x3e\x3canimateMotion dur=\"2.5s\" begin=\"1.25s\" repeatCount=\"indefinite\" path=\"M76 55 L264 55\" /\x3e\x3c/circle\x3e");
lines.push("              \x3ccircle cx=\"296\" cy=\"55\" r=\"30\" fill={isDark ? \x27#2a1a0d\x27 : \x27#fff8e1\x27} stroke={t.warn} strokeWidth=\"1.5\" /\x3e");
lines.push("              \x3ctext x=\"296\" y=\"50\" fill={t.warn} fontSize=\"10\" fontWeight=\"700\" textAnchor=\"middle\" fontFamily=\"JetBrains Mono, monospace\"\x3eBANKS\x3c/text\x3e");
lines.push("              \x3ctext x=\"296\" y=\"64\" fill={t.textGhost} fontSize=\"8\" textAnchor=\"middle\" fontFamily=\"JetBrains Mono, monospace\"\x3ePrimary\x3c/text\x3e");
lines.push("            \x3c/svg\x3e");
lines.push("            {/* Liquidity pulse bar */}");
lines.push("            \x3cdiv style={{ marginBottom: 12 }}\x3e");
lines.push("              \x3cdiv style={{ display: \x27flex\x27, justifyContent: \x27space-between\x27, fontSize: 11, color: t.textGhost, marginBottom: 4 }}\x3e");
lines.push("                \x3cspan style={{ textTransform: \x27uppercase\x27, letterSpacing: \x270.06em\x27 }}\x3eLiquidity Flow\x3c/span\x3e");
lines.push("                {walcl && \x3cspan style={{ color: t.accent, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22 }}\x3e\x24{(walcl / 1000).toFixed(2)}T WALCL\x3c/span\x3e}");
lines.push("              \x3c/div\x3e");
lines.push("              \x3cdiv style={{ height: 4, background: t.borderDim, borderRadius: 2, overflow: \x27hidden\x27, position: \x27relative\x27 }}\x3e");
lines.push("                \x3cdiv style={{ position: \x27absolute\x27, top: 0, left: 0, height: \x27100%\x27, width: 40, background: t.accent, borderRadius: 2, animation: \x27moneyFlow 2.5s linear infinite\x27 }} /\x3e");
lines.push("              \x3c/div\x3e");
lines.push("            \x3c/div\x3e");
lines.push("            {/* Key stats */}");
lines.push("            \x3cdiv style={{ display: \x27grid\x27, gridTemplateColumns: \x271fr 1fr\x27, gap: 8 }}\x3e");
lines.push("              {walcl \!= null && (");
lines.push("                \x3cdiv style={{ padding: \x278px 10px\x27, border: \x601px solid \x24{t.borderDim}\x60, borderLeft: \x602px solid \x24{t.accent}\x60 }}\x3e");
lines.push("                  \x3cdiv style={{ fontSize: 10, color: t.textGhost, textTransform: \x27uppercase\x27, letterSpacing: \x270.08em\x27, marginBottom: 2 }}\x3eBalance Sheet\x3c/div\x3e");
lines.push("                  \x3cdiv style={{ fontSize: 14, fontWeight: 700, color: t.accent, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22 }}\x3e\x24{(walcl / 1000).toFixed(2)}T\x3c/div\x3e");
lines.push("                \x3c/div\x3e");
lines.push("              )}");
lines.push("              {netLiq \!= null && (");
lines.push("                \x3cdiv style={{ padding: \x278px 10px\x27, border: \x601px solid \x24{t.borderDim}\x60, borderLeft: \x602px solid \x24{netLiqColor}\x60 }}\x3e");
lines.push("                  \x3cdiv style={{ fontSize: 10, color: t.textGhost, textTransform: \x27uppercase\x27, letterSpacing: \x270.08em\x27, marginBottom: 2 }}\x3eNet Liquidity\x3c/div\x3e");
lines.push("                  \x3cdiv style={{ fontSize: 14, fontWeight: 700, color: netLiqColor, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22 }}\x3e{netLiq \x3e 0 ? \x27+\x27 : \x27\x27}\x24{Math.abs(netLiq / 1000).toFixed(2)}T\x3c/div\x3e");
lines.push("                \x3c/div\x3e");
lines.push("              )}");
lines.push("              {latest?.macro?.fedWatchCut \!= null && (");
lines.push("                \x3cdiv style={{ padding: \x278px 10px\x27, border: \x601px solid \x24{t.borderDim}\x60, borderLeft: \x602px solid \x24{t.textDim}\x60 }}\x3e");
lines.push("                  \x3cdiv style={{ fontSize: 10, color: t.textGhost, textTransform: \x27uppercase\x27, letterSpacing: \x270.08em\x27, marginBottom: 2 }}\x3eCut Probability\x3c/div\x3e");
lines.push("                  \x3cdiv style={{ fontSize: 14, fontWeight: 700, color: latest.macro.fedWatchCut \x3e 50 ? t.accent : t.textSecondary, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22 }}\x3e{latest.macro.fedWatchCut}%\x3c/div\x3e");
lines.push("                \x3c/div\x3e");
lines.push("              )}");
lines.push("              {latest?.macro?.nextFomc && (");
lines.push("                \x3cdiv style={{ padding: \x278px 10px\x27, border: \x601px solid \x24{t.borderDim}\x60, borderLeft: \x602px solid \x24{t.textDim}\x60 }}\x3e");
lines.push("                  \x3cdiv style={{ fontSize: 10, color: t.textGhost, textTransform: \x27uppercase\x27, letterSpacing: \x270.08em\x27, marginBottom: 2 }}\x3eNext FOMC\x3c/div\x3e");
lines.push("                  \x3cdiv style={{ fontSize: 13, fontWeight: 700, color: t.textSecondary, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22 }}\x3e{latest.macro.nextFomc}\x3c/div\x3e");
lines.push("                \x3c/div\x3e");
lines.push("              )}");
lines.push("            \x3c/div\x3e");
lines.push("          \x3c/div\x3e");
lines.push("        \x3c/div\x3e");
lines.push("");
lines.push("        {/* \u2500\u2500 LIVE NEWS FEED (full-width) \u2500\u2500 */}");
lines.push("        \x3cdiv style={{ marginTop: 12, border: \x601px solid \x24{t.borderMid}\x60, background: t.panel, padding: 14, animation: \x27radarFadeUp 0.4s ease-out 0.6s both\x27 }}\x3e");
lines.push("          \x3cdiv style={{ display: \x27flex\x27, justifyContent: \x27space-between\x27, alignItems: \x27center\x27, marginBottom: 12 }}\x3e");
lines.push("            \x3cspan style={{ fontSize: 15, color: t.textSecondary, textTransform: \x27uppercase\x27, letterSpacing: \x270.1em\x27, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22, fontWeight: 700 }}\x3eLive News Feed\x3c/span\x3e");
lines.push("            \x3cdiv style={{ display: \x27flex\x27, alignItems: \x27center\x27, gap: 8 }}\x3e");
lines.push("              {newsLoading && \x3cspan style={{ fontSize: 15, color: t.textDim }}\x3eloading\u2026\x3c/span\x3e}");
lines.push("              {\!newsLoading && \x3cbutton onClick={loadNews} style={{ background: \x27none\x27, border: \x601px solid \x24{t.borderDim}\x60, color: t.textDim, fontSize: 15, padding: \x272px 7px\x27, cursor: \x27pointer\x27, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22, letterSpacing: \x270.06em\x27 }}\x3eREFRESH\x3c/button\x3e}");
lines.push("            \x3c/div\x3e");
lines.push("          \x3c/div\x3e");
lines.push("          \x3cdiv style={{ display: \x27grid\x27, gap: 6, maxHeight: 420, overflowY: \x27auto\x27 }}\x3e");
lines.push("            {news.length === 0 ? (");
lines.push("              \x3cdiv style={{ color: t.textDim, fontSize: 15, padding: \x2712px 0\x27 }}\x3e");
lines.push("                {newsLoading ? \x27Fetching live headlines\u2026\x27 : \x27Unable to load news. Refresh to retry.\x27}");
lines.push("              \x3c/div\x3e");
lines.push("            ) : news.slice(0, 12).map((item, i) => {");
lines.push("              const sent      = classifySentiment(item.title);");
lines.push("              const sentColor = sent === \x27Bullish\x27 ? t.accent : sent === \x27Bearish\x27 ? t.danger : t.textDim;");
lines.push("              const sentBg    = sent === \x27Bullish\x27 ? t.accentMuted : sent === \x27Bearish\x27 ? (isDark ? \x27#2D0A0A\x27 : \x27#FEE2E2\x27) : (isDark ? \x27#1a1a1a\x27 : \x27#f3f4f6\x27);");
lines.push("              const srcName   = item.source?.name || item.sourceInfo?.name || \x27CryptoCompare\x27;");
lines.push("              const ago       = item.published_on ? timeAgo(item.published_on) : \x27\x27;");
lines.push("              return (");
lines.push("                \x3ca key={i} href={item.url} target=\"_blank\" rel=\"noopener noreferrer\"");
lines.push("                  style={{ border: \x601px solid \x24{t.borderDim}\x60, borderLeft: \x602px solid \x24{sentColor}\x60, padding: \x278px 10px\x27, display: \x27block\x27, textDecoration: \x27none\x27, animation: \x60radarFadeUp 0.25s ease-out \x24{0.03 * i}s both\x60, cursor: \x27pointer\x27 }}\x3e");
lines.push("                  \x3cdiv style={{ display: \x27flex\x27, gap: 6, alignItems: \x27flex-start\x27, marginBottom: 5 }}\x3e");
lines.push("                    \x3cspan style={{ background: sentBg, color: sentColor, fontSize: 14, padding: \x272px 5px\x27, fontWeight: 700, textTransform: \x27uppercase\x27, letterSpacing: \x270.08em\x27, flexShrink: 0, marginTop: 1, fontFamily: \x22\x27JetBrains Mono\x27, monospace\x22 }}\x3e{sent}\x3c/span\x3e");
lines.push("                    \x3cdiv style={{ fontSize: 15, color: t.textPrimary, lineHeight: 1.45, fontWeight: 500 }}\x3e{item.title}\x3c/div\x3e");
lines.push("                  \x3c/div\x3e");
lines.push("                  \x3cdiv style={{ display: \x27flex\x27, gap: 8, alignItems: \x27center\x27 }}\x3e");
lines.push("                    \x3cspan style={{ fontSize: 15, color: t.textDim }}\x3e{srcName}\x3c/span\x3e");
lines.push("                    {ago && \x3cspan style={{ fontSize: 15, color: t.textGhost }}\x3e\u00b7 {ago}\x3c/span\x3e}");
lines.push("                    {item.categories && \x3cspan style={{ fontSize: 15, color: t.textGhost, marginLeft: \x27auto\x27 }}\x3e{item.categories.split(\x27|\x27).slice(0, 3).join(\x27 \u00b7 \x27)}\x3c/span\x3e}");
lines.push("                  \x3c/div\x3e");
lines.push("                \x3c/a\x3e");
lines.push("              );");
lines.push("            })}");
lines.push("          \x3c/div\x3e");
lines.push("        \x3c/div\x3e");
const content = lines.join("\n") + "\n";
fs.writeFileSync("/Users/fortifylabs/fortifyos-main-2/scripts/new_content.jsx", content, "utf8");
process.stdout.write("OK: " + content.length + " chars\n");
